# Generated by Django 6.1.1 on 2026-09-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_alter_menureport_receiver"),
    ]

    operations = [
        migrations.AddField(
            model_name="menureport",
            name="feedback_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When a feedback reply was successfully sent for this report (#280)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="menureport",
            name="notification_error",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Error message if the report-received email to the receiver failed to send (#280)",
            ),
        ),
    ]
