# Generated by Django 5.0.8 on 2024-09-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tc_agreement",
            field=models.BooleanField(
                default=False, verbose_name="Termini e condizioni"
            ),
        ),
    ]
