# Generated by Django 6.1.1 on 2026-09-23 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school_menu", "0024_menuimportdraft_source"),
        ("users", "0002_user_tc_agreement"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorite_school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="favorited_by",
                to="school_menu.school",
                verbose_name="Scuola preferita",
            ),
        ),
    ]
