# Generated by Django 6.1.1 on 2026-09-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_favorite_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="newsletter_opt_in",
            field=models.BooleanField(
                default=True, verbose_name="Iscritto alla newsletter"
            ),
        ),
    ]
