[project]
name = "school_menu"
version = "0.2"
requires-python = ">= 3.12"
dependencies = [
    "crispy-tailwind",
    "django >5.0",
    "django-allauth",
    "django-crispy-forms",
    "django-import-export",
    "django-template-partials",
    "djangorestframework",
    "heroicons[django]",
    "gunicorn==21.2.0",
    "neapolitan",
    "pandas==2.2.2",
    "openpyxl==3.1.2",
    "psycopg[binary]",
    "whitenoise",
]

[project.optional-dependencies]
dev = [
    "black",
    "django-browser-reload",
    # "django-debug-toolbar",
    "django-environ",
    "django-extensions",
    "django_htmx",
    "django-tailwind-cli",
    "djlint",
    "factory_boy",
    "pre-commit",
    "pywatchman",
    "pytest",
    "pytest-django",
    "kolo",
    "ruff",
]

[tool.bandit]
skips = ["B101","B311"]


[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "B", "I"]
ignore = ["E501", "E741", "F405", "B007"]


[tool.djlint]
ignore="T002,H006"
