[supervisord]
nodaemon=true
logfile=/app/logs/supervisord.log
pidfile=/tmp/supervisord.pid

[program:web]
command=/app/.venv/bin/gunicorn core.wsgi:application --bind=0.0.0.0:80
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/logs/gunicorn.log
stderr_logfile=/app/logs/gunicorn.err.log

[program:worker]
command=/app/.venv/bin/python manage.py qcluster
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/logs/qcluster.log
stderr_logfile=/app/logs/qcluster.err.log
