# Generated by Django 5.2.7 on 2025-10-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackupRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backup_type",
                    models.CharField(
                        choices=[("database", "Database"), ("media", "Media")],
                        max_length=20,
                        verbose_name="Backup Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Started At"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Error Message"),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Duration (seconds)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Backup Run",
                "verbose_name_plural": "Backup Runs",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["-started_at"], name="django_sche_started_ed18e0_idx"
                    ),
                    models.Index(
                        fields=["status"], name="django_sche_status_fc684b_idx"
                    ),
                    models.Index(
                        fields=["backup_type"], name="django_sche_backup__145fba_idx"
                    ),
                ],
            },
        ),
    ]
