# Generated by Django 6.1.1 on 2026-09-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_scheduled_backups", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="backuprun",
            options={
                "ordering": ["-started_at"],
                "verbose_name": "Esecuzione backup",
                "verbose_name_plural": "Esecuzioni backup",
            },
        ),
        migrations.AlterField(
            model_name="backuprun",
            name="backup_type",
            field=models.CharField(
                choices=[("database", "Database"), ("media", "Media")],
                max_length=20,
                verbose_name="Tipo di backup",
            ),
        ),
        migrations.AlterField(
            model_name="backuprun",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Completato il"
            ),
        ),
        migrations.AlterField(
            model_name="backuprun",
            name="duration_seconds",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Durata (secondi)"
            ),
        ),
        migrations.AlterField(
            model_name="backuprun",
            name="error_message",
            field=models.TextField(blank=True, verbose_name="Messaggio di errore"),
        ),
        migrations.AlterField(
            model_name="backuprun",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Avviato il"),
        ),
        migrations.AlterField(
            model_name="backuprun",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "In corso"),
                    ("success", "Completato"),
                    ("failed", "Fallito"),
                ],
                default="running",
                max_length=20,
                verbose_name="Stato",
            ),
        ),
    ]
