# Generated by Django 5.0.4 on 2024-04-16 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DetailedMeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Lunedì"),
                            (2, "Martedì"),
                            (3, "Mercoledì"),
                            (4, "Giovedì"),
                            (5, "Venerdì"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "week",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Settimana 1"),
                            (2, "Settimana 2"),
                            (3, "Settimana 3"),
                            (4, "Settimana 4"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "season",
                    models.SmallIntegerField(
                        choices=[(1, "Estivo"), (2, "Invernale")], default=2
                    ),
                ),
                (
                    "type",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Standard"),
                            (2, "Gluten Free"),
                            (3, "Lactose Free"),
                            (4, "Vegan"),
                        ],
                        default=1,
                    ),
                ),
                ("first_course", models.CharField(max_length=200)),
                ("second_course", models.CharField(max_length=200)),
                ("side_dish", models.CharField(max_length=200)),
                (
                    "fruit",
                    models.CharField(default="Frutta di Stagione", max_length=200),
                ),
                ("snack", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(editable=False, max_length=200, unique=True)),
                ("city", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "scuola",
                "verbose_name_plural": "scuole",
            },
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "season_choice",
                    models.SmallIntegerField(
                        choices=[(1, "Primaverile"), (2, "Invernale")],
                        default=2,
                        verbose_name="stagione",
                    ),
                ),
                (
                    "week_bias",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(3)],
                        verbose_name="scarto",
                    ),
                ),
            ],
            options={
                "verbose_name": "impostazione",
                "verbose_name_plural": "impostazioni",
            },
        ),
        migrations.CreateModel(
            name="SimpleMeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Lunedì"),
                            (2, "Martedì"),
                            (3, "Mercoledì"),
                            (4, "Giovedì"),
                            (5, "Venerdì"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "week",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Settimana 1"),
                            (2, "Settimana 2"),
                            (3, "Settimana 3"),
                            (4, "Settimana 4"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "season",
                    models.SmallIntegerField(
                        choices=[(1, "Estivo"), (2, "Invernale")], default=2
                    ),
                ),
                (
                    "type",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Standard"),
                            (2, "Gluten Free"),
                            (3, "Lactose Free"),
                            (4, "Vegan"),
                        ],
                        default=1,
                    ),
                ),
                ("menu", models.CharField(max_length=600)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
