# Generated by Django 4.1.2 on 2022-10-12 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Week",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_course", models.CharField(max_length=200)),
                ("second_course", models.CharField(max_length=200)),
                ("side_dish", models.CharField(max_length=200)),
                (
                    "fruit",
                    models.CharField(default="Frutta di Stagione", max_length=200),
                ),
                ("snack", models.CharField(max_length=200)),
                (
                    "day",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Lunedì"),
                            (2, "Martedì"),
                            (3, "Mercoledì"),
                            (4, "Giovedì"),
                            (5, "Venerdì"),
                        ]
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to="school_menu.season",
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to="school_menu.week",
                    ),
                ),
            ],
        ),
    ]
