# Generated by Django 4.1.2 on 2022-10-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="day",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Lunedì"),
                    (2, "Martedì"),
                    (3, "Mercoledì"),
                    (4, "Giovedì"),
                    (5, "Venerdì"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="season",
            field=models.SmallIntegerField(
                choices=[(1, "Estivo"), (2, "Invernale")], default=2
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="week",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Settimana 1"),
                    (2, "Settimana 2"),
                    (3, "Settimana 3"),
                    (4, "Settimana 4"),
                ],
                default=1,
            ),
        ),
        migrations.DeleteModel(
            name="Season",
        ),
        migrations.DeleteModel(
            name="Week",
        ),
    ]
