# Generated by Django 5.0.4 on 2024-04-17 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school_menu", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="season_choice",
            field=models.SmallIntegerField(
                choices=[(1, "Primaverile"), (2, "Invernale")],
                default=2,
                verbose_name="stagione",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="week_bias",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(3)],
                verbose_name="scarto",
            ),
        ),
        migrations.DeleteModel(
            name="Settings",
        ),
    ]
