# Generated by Django 4.1.2 on 2022-10-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "school_menu",
            "0002_alter_meal_day_alter_meal_season_alter_meal_week_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="type",
            field=models.SmallIntegerField(
                choices=[(1, "Standard"), (2, "Gluten Free"), (3, "Lactose Free")],
                default=1,
            ),
        ),
    ]
