# Generated by Django 4.1.2 on 2023-04-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school_menu", "0003_meal_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "season_choice",
                    models.SmallIntegerField(
                        choices=[(1, "Estivo"), (2, "Invernale")], default=2
                    ),
                ),
            ],
        ),
    ]
