# Generated by Django 5.0.4 on 2024-04-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school_menu", "0004_school_menu_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simplemeal",
            name="menu",
            field=models.TextField(max_length=600),
        ),
    ]
