# Generated by Django 4.1.2 on 2023-04-18 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school_menu", "0004_settings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="settings",
            options={"verbose_name": "stagione", "verbose_name_plural": "stagioni"},
        ),
        migrations.AddField(
            model_name="settings",
            name="week_bias",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(3)],
                verbose_name="scarto",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="season_choice",
            field=models.SmallIntegerField(
                choices=[(1, "Estivo"), (2, "Invernale")],
                default=2,
                verbose_name="stagione",
            ),
        ),
    ]
