# Generated by Django 5.0.6 on 2024-07-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school_menu", "0007_simplemeal_snack"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="season_choice",
            field=models.SmallIntegerField(
                choices=[(1, "Primaverile"), (2, "Invernale"), (3, "Automatica")],
                default=3,
                verbose_name="stagione",
            ),
        ),
    ]
