# Generated by Django 5.0.8 on 2024-08-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school_menu", "0008_alter_school_season_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
    ]
