# Generated by Django 5.1.3 on 2024-12-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school_menu", "0009_school_is_published"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simplemeal",
            name="snack",
        ),
        migrations.AddField(
            model_name="simplemeal",
            name="afternoon_snack",
            field=models.CharField(blank=True, default="-", max_length=200),
        ),
        migrations.AddField(
            model_name="simplemeal",
            name="morning_snack",
            field=models.CharField(blank=True, default="-", max_length=200),
        ),
    ]
