# Generated by Django 5.1.3 on 2024-12-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "school_menu",
            "0010_remove_simplemeal_snack_simplemeal_afternoon_snack_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="simplemeal",
            name="afternoon_snack",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="simplemeal",
            name="morning_snack",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
