# Generated by Django 5.1.4 on 2024-12-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school_menu", "0013_alter_detailedmeal_type_alter_simplemeal_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="detailedmeal",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="school",
            name="annual_menu",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="simplemeal",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
