# Generated by Django 5.1.4 on 2024-12-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school_menu", "0014_detailedmeal_date_school_annual_menu_simplemeal_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detailedmeal",
            name="season",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "Estivo"), (2, "Invernale")],
                default=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="simplemeal",
            name="season",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "Estivo"), (2, "Invernale")],
                default=2,
                null=True,
            ),
        ),
    ]
