# Generated by Django 5.1.4 on 2024-12-24 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "school_menu",
            "0016_remove_detailedmeal_date_remove_simplemeal_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="annualmeal",
            options={"ordering": ["-date"]},
        ),
    ]
