# Generated by Django 5.1.4 on 2024-12-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school_menu", "0017_alter_annualmeal_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="annualmeal",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
