# Generated by Django 5.2.4 on 2025-08-03 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school_menu", "0018_annualmeal_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="end_day",
            field=models.PositiveSmallIntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
                verbose_name="Giorno fine anno scolastico",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="end_month",
            field=models.PositiveSmallIntegerField(
                default=6,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="Mese fine anno scolastico",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="start_day",
            field=models.PositiveSmallIntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
                verbose_name="Giorno inizio anno scolastico",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="start_month",
            field=models.PositiveSmallIntegerField(
                default=9,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="Mese inizio anno scolastico",
            ),
        ),
    ]
