# Generated by Django 5.2.7 on 2025-10-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "school_menu",
            "0019_school_end_day_school_end_month_school_start_day_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="annualmeal",
            index=models.Index(
                fields=["school", "date", "is_active"], name="annual_sch_date_active"
            ),
        ),
        migrations.AddIndex(
            model_name="detailedmeal",
            index=models.Index(
                fields=["school", "week", "season"], name="detailed_sch_week_season"
            ),
        ),
        migrations.AddIndex(
            model_name="simplemeal",
            index=models.Index(
                fields=["school", "week", "season"], name="simple_sch_week_season"
            ),
        ),
    ]
