# Generated by Django 5.2.8 on 2025-11-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school_menu", "0020_annualmeal_annual_sch_date_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detailedmeal",
            name="first_course",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="detailedmeal",
            name="fruit",
            field=models.CharField(
                blank=True, default="Frutta di Stagione", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="detailedmeal",
            name="second_course",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="detailedmeal",
            name="side_dish",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="detailedmeal",
            name="snack",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
