# Generated by Django 6.0.1 on 2026-01-30 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school_menu", "0021_alter_detailedmeal_first_course_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("SCHOOL_CREATE", "Scuola creata"),
                            ("SCHOOL_UPDATE", "Scuola aggiornata"),
                            ("SCHOOL_DELETE", "Scuola eliminata"),
                            ("MENU_UPLOAD", "Menu caricato"),
                            ("MENU_DELETE", "Menu eliminato"),
                            ("SETTINGS_CHANGE", "Impostazioni modificate"),
                        ],
                        max_length=50,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("changes", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "audit log",
                "verbose_name_plural": "audit logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["-timestamp"], name="audit_timestamp_idx"),
                    models.Index(
                        fields=["user", "-timestamp"], name="audit_user_time_idx"
                    ),
                    models.Index(
                        fields=["action", "-timestamp"], name="audit_action_time_idx"
                    ),
                ],
            },
        ),
    ]
