# Generated by Django 6.1 on 2026-08-12 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import school_menu.models


class Migration(migrations.Migration):
    dependencies = [
        ("school_menu", "0022_auditlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuImportDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OFFERED", "Proposto"),
                            ("PENDING", "In elaborazione"),
                            ("READY", "Pronto"),
                            ("FAILED", "Fallito"),
                            ("CONFIRMED", "Confermato"),
                        ],
                        default="OFFERED",
                        max_length=10,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("S", "Semplice"),
                            ("D", "Dettagliato"),
                            ("A", "Annuale"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("S", "Standard"),
                            ("G", "No Glutine"),
                            ("L", "No Lattosio"),
                            ("V", "Vegetariano"),
                            ("P", "Speciale"),
                        ],
                        default="S",
                        max_length=1,
                    ),
                ),
                (
                    "season",
                    models.SmallIntegerField(
                        blank=True, choices=[(1, "Estivo"), (2, "Invernale")], null=True
                    ),
                ),
                (
                    "source_file",
                    models.FileField(
                        blank=True, upload_to=school_menu.models.menu_import_upload_to
                    ),
                ),
                ("source_filename", models.CharField(max_length=255)),
                ("source_size", models.PositiveIntegerField(default=0)),
                ("rows", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("error_code", models.CharField(blank=True, max_length=30)),
                ("error_message", models.TextField(blank=True)),
                ("task_id", models.CharField(blank=True, max_length=32)),
                ("usage", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_import_drafts",
                        to="school_menu.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_import_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "bozza di importazione",
                "verbose_name_plural": "bozze di importazione",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="draft_user_created_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"], name="draft_status_time_idx"
                    ),
                    models.Index(
                        fields=["school", "status"], name="draft_school_status_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MenuImportQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_import_quotas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "quota di importazione",
                "verbose_name_plural": "quote di importazione",
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date"), name="unique_user_quota_per_day"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", True)),
                        fields=("date",),
                        name="unique_global_quota_per_day",
                    ),
                ],
            },
        ),
    ]
