# Generated by Django 6.1 on 2026-08-17 14:10

from django.db import migrations, models


def mark_existing_drafts_as_ai(apps, schema_editor):
    """Before #254 a draft could only come from the AI, so the new default would lie."""
    apps.get_model("school_menu", "MenuImportDraft").objects.update(source="ai")


class Migration(migrations.Migration):
    dependencies = [
        ("school_menu", "0023_menuimportdraft_menuimportquota"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuimportdraft",
            name="source",
            field=models.CharField(
                choices=[("csv", "CSV"), ("ai", "Assistente")],
                default="csv",
                max_length=3,
            ),
        ),
        migrations.RunPython(
            mark_existing_drafts_as_ai, migrations.RunPython.noop, elidable=True
        ),
    ]
