# Generated by Django 6.1.1 on 2026-09-26 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school_menu", "0024_menuimportdraft_source"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="annualmeal",
            options={
                "ordering": ["-date"],
                "verbose_name": "menu annuale",
                "verbose_name_plural": "menu annuali",
            },
        ),
        migrations.AlterModelOptions(
            name="detailedmeal",
            options={
                "verbose_name": "menu dettagliato",
                "verbose_name_plural": "menu dettagliati",
            },
        ),
        migrations.AlterModelOptions(
            name="simplemeal",
            options={
                "verbose_name": "menu semplice",
                "verbose_name_plural": "menu semplici",
            },
        ),
    ]
