# Generated by Django 6.1.1 on 2026-09-27 10:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "school_menu",
            "0025_alter_annualmeal_options_alter_detailedmeal_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "registro delle modifiche",
                "verbose_name_plural": "registri delle modifiche",
            },
        ),
    ]
