# Generated by Django 5.2.2 on 2025-06-12 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("school_menu", "0018_annualmeal_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymousMenuNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subscription_info", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anonymous_notifications",
                        to="school_menu.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anonymous Menu Notification",
                "verbose_name_plural": "Anonymous Menu Notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
