# Generated by Django 5.2.4 on 2025-08-01 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_anonymousmenunotification_daily_notification"),
        ("school_menu", "0018_annualmeal_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymousmenunotification",
            name="notification_time",
            field=models.CharField(
                choices=[
                    ("previous_day_6pm", "Alle 18:00 del giorno prima"),
                    ("same_day_9am", "Alle 9:00 del giorno stesso"),
                    ("same_day_12pm", "Alle 12:00 del giorno stesso"),
                    ("same_day_6pm", "Alle 18:00 del giorno stesso"),
                ],
                default="previous_day_6pm",
                max_length=20,
                verbose_name="Orario di notifica",
            ),
        ),
        migrations.CreateModel(
            name="DailyNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_notifications",
                        to="school_menu.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Notification",
                "verbose_name_plural": "Daily Notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
