# Generated by Django 5.2.4 on 2025-08-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_anonymousmenunotification_notification_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anonymousmenunotification",
            name="notification_time",
            field=models.CharField(
                choices=[
                    ("previous_day_6pm", "alle 18:00 del giorno prima"),
                    ("same_day_9am", "alle 9:00"),
                    ("same_day_12pm", "alle 12:00"),
                    ("same_day_6pm", "alle 18:00"),
                ],
                default="same_day_12pm",
                max_length=20,
                verbose_name="Orario di notifica",
            ),
        ),
    ]
