# Generated by Django 5.2.4 on 2025-08-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_alter_anonymousmenunotification_notification_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anonymousmenunotification",
            name="daily_notification",
            field=models.BooleanField(default=True),
        ),
    ]
