# Generated by Django 5.2.7 on 2025-11-04 11:35

import hashlib

from django.db import migrations, models


def populate_subscription_endpoints(apps, schema_editor):
    """
    Populate subscription_endpoint field from subscription_info for existing records
    and remove duplicates (keeping the most recent)
    """
    AnonymousMenuNotification = apps.get_model(
        "notifications", "AnonymousMenuNotification"
    )

    # Track endpoints we've seen
    seen_endpoints = {}
    subscriptions_to_delete = []

    # Get all subscriptions ordered by created_at (newest first)
    for subscription in AnonymousMenuNotification.objects.all().order_by("-created_at"):
        subscription_info = subscription.subscription_info

        # Extract endpoint from subscription_info
        if isinstance(subscription_info, dict):
            endpoint = subscription_info.get("endpoint", "")
        else:
            endpoint = ""

        if not endpoint:
            # If no endpoint, delete this subscription as it's invalid
            subscriptions_to_delete.append(subscription.pk)
            continue

        # Generate hash
        endpoint_hash = hashlib.sha256(endpoint.encode("utf-8")).hexdigest()

        if endpoint_hash in seen_endpoints:
            # Duplicate found - mark for deletion (we keep the most recent)
            subscriptions_to_delete.append(subscription.pk)
        else:
            # First time seeing this endpoint - keep it and set the hash
            subscription.subscription_endpoint = endpoint_hash
            subscription.save(update_fields=["subscription_endpoint"])
            seen_endpoints[endpoint_hash] = subscription.pk

    # Delete duplicates and invalid subscriptions
    if subscriptions_to_delete:
        AnonymousMenuNotification.objects.filter(
            pk__in=subscriptions_to_delete
        ).delete()


def reverse_populate_subscription_endpoints(apps, schema_editor):
    """
    Reverse migration - just clear the subscription_endpoint field
    """
    AnonymousMenuNotification = apps.get_model(
        "notifications", "AnonymousMenuNotification"
    )
    AnonymousMenuNotification.objects.all().update(subscription_endpoint=None)


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0005_alter_anonymousmenunotification_daily_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymousmenunotification",
            name="subscription_endpoint",
            field=models.CharField(
                blank=True,
                help_text="SHA256 hash of the push subscription endpoint for uniqueness",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(
            populate_subscription_endpoints,
            reverse_populate_subscription_endpoints,
        ),
    ]
