# Generated by Django 5.2.7 on 2025-11-04 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0006_anonymousmenunotification_subscription_endpoint"),
        ("school_menu", "0020_annualmeal_annual_sch_date_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BroadcastNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Notification title", max_length=100),
                ),
                ("message", models.TextField(help_text="Notification body text")),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Optional URL when notification is clicked",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipients_count",
                    models.IntegerField(
                        default=0, help_text="Number of notifications sent"
                    ),
                ),
                ("success_count", models.IntegerField(default=0)),
                ("failure_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_schools",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave empty to send to all schools",
                        to="school_menu.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Broadcast Notification",
                "verbose_name_plural": "Broadcast Notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
