# Generated by Django 6.0.3 on 2026-04-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0007_broadcastnotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymousmenunotification",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("S", "Standard"),
                    ("G", "No Glutine"),
                    ("L", "No Lattosio"),
                    ("V", "Vegetariano"),
                    ("P", "Speciale"),
                ],
                default="S",
                max_length=1,
                verbose_name="Tipo di menu",
            ),
        ),
    ]
