# Generated by Django 6.1.1 on 2026-09-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0008_anonymousmenunotification_meal_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailynotification",
            name="school",
        ),
        migrations.AddField(
            model_name="dailynotification",
            name="failed_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailynotification",
            name="notification_time",
            field=models.CharField(
                choices=[
                    ("previous_day_6pm", "alle 18:00 del giorno prima"),
                    ("same_day_9am", "alle 9:00"),
                    ("same_day_12pm", "alle 12:00"),
                    ("same_day_6pm", "alle 18:00"),
                ],
                default="same_day_12pm",
                max_length=20,
                verbose_name="Orario di notifica",
            ),
        ),
        migrations.AddField(
            model_name="dailynotification",
            name="pruned_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailynotification",
            name="sent_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
