# Generated by Django 6.1.1 on 2026-09-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0009_remove_dailynotification_school_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationDeliveryMarker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subscription_endpoint", models.CharField(max_length=64)),
                ("target_date", models.DateField()),
                (
                    "notification_time",
                    models.CharField(
                        choices=[
                            ("previous_day_6pm", "alle 18:00 del giorno prima"),
                            ("same_day_9am", "alle 9:00"),
                            ("same_day_12pm", "alle 12:00"),
                            ("same_day_6pm", "alle 18:00"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Notification Delivery Marker",
                "verbose_name_plural": "Notification Delivery Markers",
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "subscription_endpoint",
                            "target_date",
                            "notification_time",
                        ),
                        name="unique_notification_delivery_marker",
                    )
                ],
            },
        ),
    ]
