# Generated by Django 6.1.1 on 2026-09-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0010_notificationdeliverymarker"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyDigest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("new_schools", models.PositiveIntegerField(default=0)),
                ("menu_reports", models.PositiveIntegerField(default=0)),
                ("report_errors", models.PositiveIntegerField(default=0)),
                ("feedback_sent", models.PositiveIntegerField(default=0)),
                ("new_subscriptions", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Monthly Digest",
                "verbose_name_plural": "Monthly Digests",
                "ordering": ["-period_start"],
            },
        ),
    ]
