# Generated by Django 6.1.1 on 2026-09-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0012_newsletter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="body_html",
            field=models.TextField(
                default='<p style="margin:0 0 16px; font-size:15px; line-height:1.6; color:#1f2937;">\n  Primo paragrafo: scrivi qui l\'introduzione della newsletter.\n</p>\n<p style="margin:0 0 16px; font-size:15px; line-height:1.6; color:#1f2937;">\n  Secondo paragrafo: scrivi qui ulteriori dettagli o contesto.\n</p>\n<p style="margin:0 0 8px; font-size:15px; line-height:1.6; color:#1f2937; font-weight:600;">\n  Novità di questo aggiornamento:\n</p>\n<ul style="margin:0 0 16px; padding-left:20px; font-size:15px; line-height:1.6; color:#1f2937;">\n  <li style="margin-bottom:6px;">Prima nuova funzionalità</li>\n  <li style="margin-bottom:6px;">Seconda nuova funzionalità</li>\n  <li style="margin-bottom:6px;">Terza nuova funzionalità</li>\n</ul>',
                help_text="Raw HTML for the content area only: the header bar and the unsubscribe link are added automatically by the mail template.",
            ),
        ),
    ]
