# Generated by Django 6.1.1 on 2026-09-26 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0013_alter_newsletter_body_html"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anonymousmenunotification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Notifica anonima menu",
                "verbose_name_plural": "Notifiche anonime menu",
            },
        ),
        migrations.AlterModelOptions(
            name="broadcastnotification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Notifica broadcast",
                "verbose_name_plural": "Notifiche broadcast",
            },
        ),
        migrations.AlterModelOptions(
            name="dailynotification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Notifica giornaliera",
                "verbose_name_plural": "Notifiche giornaliere",
            },
        ),
        migrations.AlterModelOptions(
            name="monthlydigest",
            options={
                "ordering": ["-period_start"],
                "verbose_name": "Riepilogo mensile",
                "verbose_name_plural": "Riepiloghi mensili",
            },
        ),
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Newsletter",
                "verbose_name_plural": "Newsletter",
            },
        ),
        migrations.AlterModelOptions(
            name="notificationdeliverymarker",
            options={
                "verbose_name": "Marcatore invio notifica",
                "verbose_name_plural": "Marcatori invio notifica",
            },
        ),
    ]
