name: Tests Runner
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-22.04
    env:
      ADMIN_EMAIL: admin@example.com
      ALLOWED_HOSTS: '*'
      CSRF_TRUSTED_ORIGINS: http://localhost:8000
      DROPBOX_OAUTH2_ACCESS_TOKEN: '123'
      DROPBOX_OAUTH2_REFRESH_TOKEN: '123'
      DROPBOX_APP_SECRET: '123'
      DROPBOX_APP_KEY: '123'
      ENVIRONMENT: test
      MAILGUN_API_KEY: key-123
      MAILGUN_API_URL: http://localhost:8000
      MAILGUN_SENDER_DOMAIN: sandbox123.mailgun.org
      SECRET_KEY: a secret to everybody
      VAPID_PRIVATE_KEY: '123'
      VAPID_PUBLIC_KEY: '123'



    steps:
    - name: Get the code
      uses: actions/checkout@v3

    - name: Install astral/uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        github-token: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Install Python
      run: uv python install

    - name: Install Packages
      run: uv sync --all-extras

    - name: Test it
      run: uv run pytest -n 8 --reuse-db --dist loadscope --exitfirst
