name: Tests Runner
on:
  push:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-22.04
    env:
      ALLOWED_HOSTS: '*'
      DEBUG: 'on'
      SECRET_KEY: 'a secret to everybody'
      NO_RELOAD: 'on'

    steps:
      - name: Get the code
        uses: actions/checkout@v3

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python packages
        uses: yezz123/setup-uv@v4
        with:
          uv-venv: ".venv"
      - run: uv pip install -r requirements.txt -r requirements-dev.txt

      - name: Test it
        run: task test

      # - name: Check deploy configuration
      #   run: ./manage.py check --deploy --fail-level WARNING
      #   env:
      #     DATABASE_URL: 'sqlite://:memory:'
      #     SECRET_KEY: 'zt(6jlr#oquxm2t%ryh#n+-72p^(3knbf&q$5x16#o%1im-s7!'
      #     SECURE_SSL_REDIRECT: 'on'
